package constants

var ErrorStringApi errorStringApi

type errorStringApi struct {
  INVALID_REQUEST string
  INTERNAL_ERROR string

  UNAUTHORIZED_ACCESS string
  AUTH_TOKEN_FAIL string
  AUTH_TOKEN_TIMEOUT string
  AUTH_TOKEN_INVALID string

  USER_NOT_FOUND string
  USER_EXISTED string
  USER_TOKEN_GEN_FAILED string
}

func init() {
  ErrorStringApi = errorStringApi{
    INVALID_REQUEST: "INVALID_REQUEST",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    AUTH_TOKEN_FAIL: "AUTH_TOKEN_FAIL",
    AUTH_TOKEN_TIMEOUT: "AUTH_TOKEN_TIMEOUT",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_EXISTED: "USER_EXISTED",
    USER_TOKEN_GEN_FAILED: "USER_TOKEN_GEN_FAILED",
  }
}